// Integrations catalog — uses real brand logos via Clearbit Logo API (logo.clearbit.com/<domain>).
// Clearbit returns the real, color-accurate logo for nearly every public company.

import { generatedIntegrations } from "./integrationsCatalog.generated";

export type IntegrationType = "oauth" | "notification" | "service" | "pipedream";

export interface Integration {
  id: string;
  name: string;
  description: string;
  category: string;
  app: string;
  type: IntegrationType;
  pipedreamSlug?: string;
  domain?: string; // e.g. "notion.so" — used to fetch real logo
}

export const INTEGRATION_CATEGORIES = [
  "All",
  "Development",
  "Productivity",
  "Communication",
  "Marketing",
  "Storage",
  "Notifications",
  "Deployment",
  "Analytics",
  "Social",
  "Design",
  "Support",
  "Payments",
  "Scheduling",
  "Automation",
] as const;

/** Hand-curated, first-class integrations. Always shown first. */
export const curatedIntegrations: Integration[] = [
  // ── Native (first-party) ──
  {
    id: "github",
    name: "GitHub",
    description: "Push code, create repos, and read repositories.",
    category: "Development",
    app: "github",
    type: "pipedream",
    pipedreamSlug: "github",
    domain: "github.com",
  },
  {
    id: "supabase",
    name: "Supabase",
    description: "Link your Supabase account to manage projects, data, and migrations.",
    category: "Development",
    app: "supabase",
    type: "pipedream",
    pipedreamSlug: "supabase_management_api",
    domain: "supabase.com",
  },
  {
    id: "email",
    name: "Email (Resend)",
    description: "Receive important updates by email via Resend.",
    category: "Notifications",
    app: "email",
    type: "notification",
    domain: "resend.com",
  },
  {
    id: "telegram",
    name: "Telegram",
    description: "Receive notifications and chat with the bot on Telegram.",
    category: "Notifications",
    app: "telegram",
    type: "notification",
    domain: "telegram.org",
  },
  {
    id: "cloudflare",
    name: "Cloudflare Pages",
    description: "Deploy your apps to Cloudflare Pages.",
    category: "Deployment",
    app: "cloudflare",
    type: "service",
    domain: "cloudflare.com",
  },

  // ── Productivity ──
  {
    id: "google_sheets",
    name: "Google Sheets",
    description: "Read and write data in your spreadsheets.",
    category: "Productivity",
    app: "google_sheets",
    type: "pipedream",
    pipedreamSlug: "google_sheets",
    domain: "sheets.google.com",
  },
  {
    id: "google_docs",
    name: "Google Docs",
    description: "Create and edit documents programmatically.",
    category: "Productivity",
    app: "google_docs",
    type: "pipedream",
    pipedreamSlug: "google_docs",
    domain: "docs.google.com",
  },
  {
    id: "google_calendar",
    name: "Google Calendar",
    description: "Manage events and check availability.",
    category: "Productivity",
    app: "google_calendar",
    type: "pipedream",
    pipedreamSlug: "google_calendar",
    domain: "calendar.google.com",
  },
  {
    id: "google_forms",
    name: "Google Forms",
    description: "Read submissions from your forms.",
    category: "Productivity",
    app: "google_forms",
    type: "pipedream",
    pipedreamSlug: "google_forms",
    domain: "forms.google.com",
  },
  {
    id: "notion",
    name: "Notion",
    description: "Create pages, query databases, and update content.",
    category: "Productivity",
    app: "notion",
    type: "pipedream",
    pipedreamSlug: "notion",
    domain: "notion.so",
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Read and write bases and records.",
    category: "Productivity",
    app: "airtable_oauth",
    type: "pipedream",
    pipedreamSlug: "airtable_oauth",
    domain: "airtable.com",
  },
  {
    id: "trello",
    name: "Trello",
    description: "Create and update boards, lists, and cards.",
    category: "Productivity",
    app: "trello",
    type: "pipedream",
    pipedreamSlug: "trello",
    domain: "trello.com",
  },
  {
    id: "asana",
    name: "Asana",
    description: "Create and update tasks and projects.",
    category: "Productivity",
    app: "asana",
    type: "pipedream",
    pipedreamSlug: "asana",
    domain: "asana.com",
  },
  {
    id: "clickup",
    name: "ClickUp",
    description: "Manage tasks, lists, and docs.",
    category: "Productivity",
    app: "clickup",
    type: "pipedream",
    pipedreamSlug: "clickup",
    domain: "clickup.com",
  },
  {
    id: "monday",
    name: "Monday.com",
    description: "Update items and boards on Monday.",
    category: "Productivity",
    app: "monday",
    type: "pipedream",
    pipedreamSlug: "monday",
    domain: "monday.com",
  },
  {
    id: "todoist",
    name: "Todoist",
    description: "Create, complete, and organize tasks.",
    category: "Productivity",
    app: "todoist",
    type: "pipedream",
    pipedreamSlug: "todoist",
    domain: "todoist.com",
  },
  {
    id: "evernote",
    name: "Evernote",
    description: "Capture and search your notes.",
    category: "Productivity",
    app: "evernote",
    type: "pipedream",
    pipedreamSlug: "evernote",
    domain: "evernote.com",
  },
  {
    id: "obsidian",
    name: "Obsidian",
    description: "Sync notes with your Obsidian vault.",
    category: "Productivity",
    app: "obsidian",
    type: "pipedream",
    pipedreamSlug: "obsidian",
    domain: "obsidian.md",
  },
  {
    id: "coda",
    name: "Coda",
    description: "Update docs, tables, and rows.",
    category: "Productivity",
    app: "coda",
    type: "pipedream",
    pipedreamSlug: "coda",
    domain: "coda.io",
  },

  // ── Communication ──
  {
    id: "gmail",
    name: "Gmail",
    description: "Send and read emails on your behalf.",
    category: "Communication",
    app: "gmail",
    type: "pipedream",
    pipedreamSlug: "gmail",
    domain: "mail.google.com",
  },
  {
    id: "slack",
    name: "Slack",
    description: "Send messages and manage channels.",
    category: "Communication",
    app: "slack",
    type: "pipedream",
    pipedreamSlug: "slack",
    domain: "slack.com",
  },
  {
    id: "discord",
    name: "Discord",
    description: "Post to channels via your bot.",
    category: "Communication",
    app: "discord",
    type: "pipedream",
    pipedreamSlug: "discord",
    domain: "discord.com",
  },
  {
    id: "whatsapp_business",
    name: "WhatsApp Business",
    description: "Send WhatsApp messages via Cloud API.",
    category: "Communication",
    app: "whatsapp_business",
    type: "pipedream",
    pipedreamSlug: "whatsapp_business",
    domain: "whatsapp.com",
  },
  {
    id: "microsoft_teams",
    name: "Microsoft Teams",
    description: "Send messages to channels and chats.",
    category: "Communication",
    app: "microsoft_teams",
    type: "pipedream",
    pipedreamSlug: "microsoft_teams",
    domain: "teams.microsoft.com",
  },
  {
    id: "microsoft_outlook",
    name: "Outlook",
    description: "Send and manage emails on Outlook.",
    category: "Communication",
    app: "microsoft_outlook",
    type: "pipedream",
    pipedreamSlug: "microsoft_outlook",
    domain: "outlook.com",
  },
  {
    id: "zoom",
    name: "Zoom",
    description: "Schedule and manage Zoom meetings.",
    category: "Communication",
    app: "zoom",
    type: "pipedream",
    pipedreamSlug: "zoom",
    domain: "zoom.us",
  },
  {
    id: "google_meet",
    name: "Google Meet",
    description: "Create and manage Meet links.",
    category: "Communication",
    app: "google_meet",
    type: "pipedream",
    pipedreamSlug: "google_meet",
    domain: "meet.google.com",
  },
  {
    id: "twilio",
    name: "Twilio",
    description: "Send SMS and make voice calls.",
    category: "Communication",
    app: "twilio",
    type: "pipedream",
    pipedreamSlug: "twilio",
    domain: "twilio.com",
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    description: "Send transactional and marketing emails.",
    category: "Communication",
    app: "sendgrid",
    type: "pipedream",
    pipedreamSlug: "sendgrid",
    domain: "sendgrid.com",
  },
  {
    id: "mailgun",
    name: "Mailgun",
    description: "Send and receive transactional email.",
    category: "Communication",
    app: "mailgun",
    type: "pipedream",
    pipedreamSlug: "mailgun",
    domain: "mailgun.com",
  },
  {
    id: "crisp",
    name: "Crisp",
    description: "Engage visitors with live chat.",
    category: "Communication",
    app: "crisp",
    type: "pipedream",
    pipedreamSlug: "crisp",
    domain: "crisp.chat",
  },

  // ── Marketing & Sales ──
  {
    id: "hubspot",
    name: "HubSpot",
    description: "Sync contacts, deals, and tickets.",
    category: "Marketing",
    app: "hubspot",
    type: "pipedream",
    pipedreamSlug: "hubspot",
    domain: "hubspot.com",
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    description: "Manage audiences and send campaigns.",
    category: "Marketing",
    app: "mailchimp",
    type: "pipedream",
    pipedreamSlug: "mailchimp",
    domain: "mailchimp.com",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    description: "Manage leads, opportunities, and accounts.",
    category: "Marketing",
    app: "salesforce",
    type: "pipedream",
    pipedreamSlug: "salesforce_rest_api",
    domain: "salesforce.com",
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    description: "Sync deals and contacts.",
    category: "Marketing",
    app: "pipedrive",
    type: "pipedream",
    pipedreamSlug: "pipedrive",
    domain: "pipedrive.com",
  },
  {
    id: "convertkit",
    name: "Kit (ConvertKit)",
    description: "Manage subscribers and broadcasts.",
    category: "Marketing",
    app: "convertkit",
    type: "pipedream",
    pipedreamSlug: "convertkit",
    domain: "kit.com",
  },
  {
    id: "typeform",
    name: "Typeform",
    description: "Read responses and create forms.",
    category: "Marketing",
    app: "typeform",
    type: "pipedream",
    pipedreamSlug: "typeform",
    domain: "typeform.com",
  },
  {
    id: "klaviyo",
    name: "Klaviyo",
    description: "Manage subscribers and email flows.",
    category: "Marketing",
    app: "klaviyo",
    type: "pipedream",
    pipedreamSlug: "klaviyo",
    domain: "klaviyo.com",
  },
  {
    id: "activecampaign",
    name: "ActiveCampaign",
    description: "Automate marketing and CRM.",
    category: "Marketing",
    app: "activecampaign",
    type: "pipedream",
    pipedreamSlug: "activecampaign",
    domain: "activecampaign.com",
  },
  {
    id: "intercom",
    name: "Intercom",
    description: "Send messages and manage conversations.",
    category: "Support",
    app: "intercom",
    type: "pipedream",
    pipedreamSlug: "intercom",
    domain: "intercom.com",
  },

  // ── Payments & Commerce ──
  {
    id: "stripe",
    name: "Stripe",
    description: "Read customers, charges, and subscriptions.",
    category: "Payments",
    app: "stripe",
    type: "pipedream",
    pipedreamSlug: "stripe",
    domain: "stripe.com",
  },
  {
    id: "paypal",
    name: "PayPal",
    description: "Read payments and invoices.",
    category: "Payments",
    app: "paypal",
    type: "pipedream",
    pipedreamSlug: "paypal",
    domain: "paypal.com",
  },
  {
    id: "square",
    name: "Square",
    description: "Read sales and customers.",
    category: "Payments",
    app: "square",
    type: "pipedream",
    pipedreamSlug: "square",
    domain: "squareup.com",
  },
  {
    id: "shopify",
    name: "Shopify",
    description: "Manage products, orders, and customers.",
    category: "Payments",
    app: "shopify_developer_app",
    type: "pipedream",
    pipedreamSlug: "shopify_developer_app",
    domain: "shopify.com",
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    description: "Manage store orders and products.",
    category: "Payments",
    app: "woocommerce",
    type: "pipedream",
    pipedreamSlug: "woocommerce",
    domain: "woocommerce.com",
  },
  {
    id: "lemonsqueezy",
    name: "Lemon Squeezy",
    description: "Sell digital products and subscriptions.",
    category: "Payments",
    app: "lemonsqueezy",
    type: "pipedream",
    pipedreamSlug: "lemonsqueezy",
    domain: "lemonsqueezy.com",
  },

  // ── Storage ──
  {
    id: "google_drive",
    name: "Google Drive",
    description: "Upload, list, and share files in Drive.",
    category: "Storage",
    app: "google_drive",
    type: "pipedream",
    pipedreamSlug: "google_drive",
    domain: "drive.google.com",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    description: "Upload and manage files in Dropbox.",
    category: "Storage",
    app: "dropbox",
    type: "pipedream",
    pipedreamSlug: "dropbox",
    domain: "dropbox.com",
  },
  {
    id: "microsoft_onedrive",
    name: "OneDrive",
    description: "Manage files in Microsoft OneDrive.",
    category: "Storage",
    app: "microsoft_onedrive",
    type: "pipedream",
    pipedreamSlug: "microsoft_onedrive",
    domain: "onedrive.live.com",
  },
  {
    id: "box",
    name: "Box",
    description: "Manage files and folders in Box.",
    category: "Storage",
    app: "box",
    type: "pipedream",
    pipedreamSlug: "box",
    domain: "box.com",
  },
  {
    id: "aws_s3",
    name: "Amazon S3",
    description: "Upload and manage objects in S3 buckets.",
    category: "Storage",
    app: "aws",
    type: "pipedream",
    pipedreamSlug: "aws",
    domain: "aws.amazon.com",
  },

  // ── Development ──
  {
    id: "gitlab",
    name: "GitLab",
    description: "Manage repos, issues, and merge requests.",
    category: "Development",
    app: "gitlab",
    type: "pipedream",
    pipedreamSlug: "gitlab",
    domain: "gitlab.com",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    description: "Manage repositories and pull requests.",
    category: "Development",
    app: "bitbucket",
    type: "pipedream",
    pipedreamSlug: "bitbucket",
    domain: "bitbucket.org",
  },
  {
    id: "linear",
    name: "Linear",
    description: "Create and update issues in Linear.",
    category: "Development",
    app: "linear",
    type: "pipedream",
    pipedreamSlug: "linear",
    domain: "linear.app",
  },
  {
    id: "jira",
    name: "Jira",
    description: "Manage issues and projects in Jira.",
    category: "Development",
    app: "jira",
    type: "pipedream",
    pipedreamSlug: "jira",
    domain: "atlassian.com",
  },
  {
    id: "sentry",
    name: "Sentry",
    description: "Read issues and releases.",
    category: "Development",
    app: "sentry",
    type: "pipedream",
    pipedreamSlug: "sentry",
    domain: "sentry.io",
  },
  {
    id: "datadog",
    name: "Datadog",
    description: "Query metrics and incidents.",
    category: "Development",
    app: "datadog",
    type: "pipedream",
    pipedreamSlug: "datadog",
    domain: "datadoghq.com",
  },
  {
    id: "postman",
    name: "Postman",
    description: "Manage API collections.",
    category: "Development",
    app: "postman",
    type: "pipedream",
    pipedreamSlug: "postman",
    domain: "postman.com",
  },

  // ── Deployment ──
  {
    id: "vercel",
    name: "Vercel",
    description: "Trigger and inspect Vercel deployments.",
    category: "Deployment",
    app: "vercel",
    type: "pipedream",
    pipedreamSlug: "vercel",
    domain: "vercel.com",
  },
  {
    id: "netlify",
    name: "Netlify",
    description: "Trigger builds and manage sites.",
    category: "Deployment",
    app: "netlify",
    type: "pipedream",
    pipedreamSlug: "netlify",
    domain: "netlify.com",
  },
  {
    id: "render",
    name: "Render",
    description: "Manage services and deploys.",
    category: "Deployment",
    app: "render",
    type: "pipedream",
    pipedreamSlug: "render",
    domain: "render.com",
  },
  {
    id: "fly",
    name: "Fly.io",
    description: "Manage apps deployed on Fly.",
    category: "Deployment",
    app: "fly",
    type: "pipedream",
    pipedreamSlug: "fly",
    domain: "fly.io",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    description: "Manage droplets and apps.",
    category: "Deployment",
    app: "digitalocean",
    type: "pipedream",
    pipedreamSlug: "digitalocean",
    domain: "digitalocean.com",
  },
  {
    id: "railway",
    name: "Railway",
    description: "Deploy services and databases.",
    category: "Deployment",
    app: "railway",
    type: "pipedream",
    pipedreamSlug: "railway",
    domain: "railway.app",
  },

  // ── AI providers removed: the app already ships its own AI. Adding external
  //    AI providers here adds no value and confuses users. ──

  // ── Analytics ──
  {
    id: "google_analytics",
    name: "Google Analytics",
    description: "Query GA4 reports and metrics.",
    category: "Analytics",
    app: "google_analytics",
    type: "pipedream",
    pipedreamSlug: "google_analytics",
    domain: "analytics.google.com",
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    description: "Send events and read insights.",
    category: "Analytics",
    app: "mixpanel",
    type: "pipedream",
    pipedreamSlug: "mixpanel",
    domain: "mixpanel.com",
  },
  {
    id: "amplitude",
    name: "Amplitude",
    description: "Send events and query charts.",
    category: "Analytics",
    app: "amplitude",
    type: "pipedream",
    pipedreamSlug: "amplitude",
    domain: "amplitude.com",
  },
  {
    id: "posthog",
    name: "PostHog",
    description: "Product analytics and feature flags.",
    category: "Analytics",
    app: "posthog",
    type: "pipedream",
    pipedreamSlug: "posthog",
    domain: "posthog.com",
  },
  {
    id: "segment",
    name: "Segment",
    description: "Send and route customer data events.",
    category: "Analytics",
    app: "segment",
    type: "pipedream",
    pipedreamSlug: "segment",
    domain: "segment.com",
  },

  // ── Social ──
  {
    id: "linkedin",
    name: "LinkedIn",
    description: "Post updates and read profile data.",
    category: "Social",
    app: "linkedin",
    type: "pipedream",
    pipedreamSlug: "linkedin",
    domain: "linkedin.com",
  },
  {
    id: "twitter",
    name: "X (Twitter)",
    description: "Post tweets and read your timeline.",
    category: "Social",
    app: "twitter",
    type: "pipedream",
    pipedreamSlug: "twitter",
    domain: "x.com",
  },
  {
    id: "facebook_pages",
    name: "Facebook Pages",
    description: "Publish posts and read insights.",
    category: "Social",
    app: "facebook_pages",
    type: "pipedream",
    pipedreamSlug: "facebook_pages",
    domain: "facebook.com",
  },
  {
    id: "instagram",
    name: "Instagram",
    description: "Publish content and read insights.",
    category: "Social",
    app: "instagram_business",
    type: "pipedream",
    pipedreamSlug: "instagram_business",
    domain: "instagram.com",
  },
  {
    id: "youtube",
    name: "YouTube",
    description: "Upload videos and read channel stats.",
    category: "Social",
    app: "youtube_data_api",
    type: "pipedream",
    pipedreamSlug: "youtube_data_api",
    domain: "youtube.com",
  },
  {
    id: "tiktok",
    name: "TikTok",
    description: "Read your account and post videos.",
    category: "Social",
    app: "tiktok",
    type: "pipedream",
    pipedreamSlug: "tiktok",
    domain: "tiktok.com",
  },
  {
    id: "reddit",
    name: "Reddit",
    description: "Post and read from subreddits.",
    category: "Social",
    app: "reddit",
    type: "pipedream",
    pipedreamSlug: "reddit",
    domain: "reddit.com",
  },
  {
    id: "pinterest",
    name: "Pinterest",
    description: "Publish and read pins and boards.",
    category: "Social",
    app: "pinterest",
    type: "pipedream",
    pipedreamSlug: "pinterest",
    domain: "pinterest.com",
  },
  {
    id: "threads",
    name: "Threads",
    description: "Post and read Threads content.",
    category: "Social",
    app: "threads",
    type: "pipedream",
    pipedreamSlug: "threads",
    domain: "threads.net",
  },

  // ── Design ──
  {
    id: "figma",
    name: "Figma",
    description: "Read files and export design assets.",
    category: "Design",
    app: "figma",
    type: "pipedream",
    pipedreamSlug: "figma",
    domain: "figma.com",
  },
  {
    id: "webflow",
    name: "Webflow",
    description: "Manage CMS items and publish sites.",
    category: "Design",
    app: "webflow",
    type: "pipedream",
    pipedreamSlug: "webflow",
    domain: "webflow.com",
  },
  {
    id: "framer",
    name: "Framer",
    description: "Publish and update Framer sites.",
    category: "Design",
    app: "framer",
    type: "pipedream",
    pipedreamSlug: "framer",
    domain: "framer.com",
  },
  {
    id: "canva",
    name: "Canva",
    description: "Manage designs and brand kits.",
    category: "Design",
    app: "canva",
    type: "pipedream",
    pipedreamSlug: "canva",
    domain: "canva.com",
  },

  // ── Support ──
  {
    id: "zendesk",
    name: "Zendesk",
    description: "Create tickets and manage users.",
    category: "Support",
    app: "zendesk",
    type: "pipedream",
    pipedreamSlug: "zendesk",
    domain: "zendesk.com",
  },
  {
    id: "freshdesk",
    name: "Freshdesk",
    description: "Manage tickets and contacts.",
    category: "Support",
    app: "freshdesk",
    type: "pipedream",
    pipedreamSlug: "freshdesk",
    domain: "freshworks.com",
  },
  {
    id: "helpscout",
    name: "Help Scout",
    description: "Manage conversations and customers.",
    category: "Support",
    app: "helpscout",
    type: "pipedream",
    pipedreamSlug: "helpscout",
    domain: "helpscout.com",
  },

  // ── Scheduling ──
  {
    id: "calendly",
    name: "Calendly",
    description: "Read scheduled events and invitees.",
    category: "Scheduling",
    app: "calendly",
    type: "pipedream",
    pipedreamSlug: "calendly",
    domain: "calendly.com",
  },
  {
    id: "cal_com",
    name: "Cal.com",
    description: "Manage bookings and event types.",
    category: "Scheduling",
    app: "calcom",
    type: "pipedream",
    pipedreamSlug: "calcom",
    domain: "cal.com",
  },
  {
    id: "acuity",
    name: "Acuity Scheduling",
    description: "Manage appointments and clients.",
    category: "Scheduling",
    app: "acuity_scheduling",
    type: "pipedream",
    pipedreamSlug: "acuity_scheduling",
    domain: "acuityscheduling.com",
  },

  // ── Automation ──
  {
    id: "zapier",
    name: "Zapier",
    description: "Trigger Zaps from your workflows.",
    category: "Automation",
    app: "zapier",
    type: "pipedream",
    pipedreamSlug: "zapier",
    domain: "zapier.com",
  },
  {
    id: "make",
    name: "Make",
    description: "Run no-code automation scenarios.",
    category: "Automation",
    app: "make",
    type: "pipedream",
    pipedreamSlug: "make",
    domain: "make.com",
  },
  {
    id: "n8n",
    name: "n8n",
    description: "Open-source workflow automation.",
    category: "Automation",
    app: "n8n",
    type: "pipedream",
    pipedreamSlug: "n8n_io",
    domain: "n8n.io",
  },
  {
    id: "ifttt",
    name: "IFTTT",
    description: "Trigger applets from your app.",
    category: "Automation",
    app: "ifttt",
    type: "pipedream",
    pipedreamSlug: "ifttt",
    domain: "ifttt.com",
  },
  {
    id: "pipedream",
    name: "Pipedream",
    description: "Connect APIs and run workflows with code.",
    category: "Automation",
    app: "pipedream",
    type: "pipedream",
    pipedreamSlug: "pipedream",
    domain: "pipedream.com",
  },
  {
    id: "activepieces",
    name: "Activepieces",
    description: "Open-source, no-code business automation.",
    category: "Automation",
    app: "activepieces",
    type: "pipedream",
    pipedreamSlug: "activepieces",
    domain: "activepieces.com",
  },
  {
    id: "workato",
    name: "Workato",
    description: "Enterprise-grade integration and automation.",
    category: "Automation",
    app: "workato",
    type: "pipedream",
    pipedreamSlug: "workato",
    domain: "workato.com",
  },
  {
    id: "tray",
    name: "Tray.io",
    description: "Low-code general automation platform.",
    category: "Automation",
    app: "tray",
    type: "pipedream",
    pipedreamSlug: "tray",
    domain: "tray.io",
  },
  {
    id: "integrately",
    name: "Integrately",
    description: "One-click integrations between apps.",
    category: "Automation",
    app: "integrately",
    type: "pipedream",
    pipedreamSlug: "integrately",
    domain: "integrately.com",
  },
  {
    id: "pabbly",
    name: "Pabbly Connect",
    description: "Automate workflows across apps at low cost.",
    category: "Automation",
    app: "pabbly",
    type: "pipedream",
    pipedreamSlug: "pabbly_connect",
    domain: "pabbly.com",
  },
  {
    id: "albato",
    name: "Albato",
    description: "No-code integrations for SaaS apps.",
    category: "Automation",
    app: "albato",
    type: "pipedream",
    pipedreamSlug: "albato",
    domain: "albato.com",
  },
  {
    id: "relay",
    name: "Relay.app",
    description: "Human-in-the-loop AI workflow automation.",
    category: "Automation",
    app: "relay",
    type: "pipedream",
    pipedreamSlug: "relay",
    domain: "relay.app",
  },
  {
    id: "boost-space",
    name: "Boost.space",
    description: "Central data hub with automation.",
    category: "Automation",
    app: "boost-space",
    type: "pipedream",
    pipedreamSlug: "boost_space",
    domain: "boost.space",
  },
  {
    id: "apix-drive",
    name: "ApiX-Drive",
    description: "Connect apps with no coding required.",
    category: "Automation",
    app: "apix-drive",
    type: "pipedream",
    pipedreamSlug: "apix_drive",
    domain: "apix-drive.com",
  },
  {
    id: "konnectify",
    name: "Konnectify",
    description: "No-code automations for growing businesses.",
    category: "Automation",
    app: "konnectify",
    type: "pipedream",
    pipedreamSlug: "konnectify",
    domain: "konnectify.co",
  },
];

// The long tail (1000 of the most widely used business apps) is generated from
// the public Pipedream component registry, so each entry already has ready-made
// actions and triggers behind the same connect flow.
const seen = new Set<string>();
for (const item of curatedIntegrations) {
  seen.add(item.app);
  if (item.pipedreamSlug) seen.add(item.pipedreamSlug);
  seen.add(item.id);
}

export const integrations: Integration[] = [
  ...curatedIntegrations,
  ...generatedIntegrations.filter((item) => {
    if (seen.has(item.app) || seen.has(item.id) || (item.pipedreamSlug && seen.has(item.pipedreamSlug))) {
      return false;
    }
    seen.add(item.app);
    seen.add(item.id);
    if (item.pipedreamSlug) seen.add(item.pipedreamSlug);
    return true;
  }),
];
