// Shared types between client + UI for the new free-form docs agent.

export type DocsClarifyQuestionType =
  | "text"
  | "long_text"
  | "choice"
  | "multi_choice"
  | "number"
  | "date"
  | "email"
  | "phone"
  | "url"
  | "image";

export type DocsClarifyQuestion = {
  id: string;
  label: string;
  /** Short helper sentence shown under the label. */
  help?: string;
  type: DocsClarifyQuestionType;
  /** Required questions block the wizard's "next" until answered. */
  required?: boolean;
  /** For choice/multi_choice. */
  options?: string[];
  placeholder?: string;
  /** Optional grouping label for the wizard progress (e.g. "Your data", "Customer data"). */
  group?: string;
  /** Optional max length for text inputs. */
  maxLength?: number;
};

/** UI label strings for the clarify wizard, generated by the AI in the
 *  user's exact language and dialect so the chrome (title, buttons, hints)
 *  matches the way they wrote the prompt. All keys are optional — missing
 *  ones fall back to baked-in English defaults on the client. */
export type DocsClarifyUi = {
  title?: string; // e.g. "Before I start designing"
  phase?: string; // e.g. "Clarifying phase"
  back?: string;
  skip?: string;
  next?: string; // e.g. "Next question"
  startDesign?: string; // last step CTA
  answered?: string; // status pill after submit, e.g. "Got it"
  thinking?: string;
  finishEarly?: string; // "Skip to results"
  optionalHint?: string; // "Optional — feel free to skip"
  uploadCta?: string;
  orPasteUrl?: string;
  uploading?: string;
  uploaded?: string;
  uploaded2?: string;
  uploadFailed?: string;
  clear?: string;
  maxSize?: string;
};

export type DocsClarifyResponse = {
  kind: "clarify";
  reason: string;
  questions: DocsClarifyQuestion[];
  ui?: DocsClarifyUi;
};

export type DocsHtmlResponse = {
  kind: "html";
  doc_type: string;
  title: string;
  html: string;
};

export type DocsGenerateResponse = DocsClarifyResponse | DocsHtmlResponse;

export type DocsArtifactMeta = {
  artifactId: string;
  title: string;
  doc_type: string;
  html: string;
  createdAt: number;
};
