// 200+ short English phrases Megsy whispers when the user starts typing.
// Use {name} as a placeholder — it will be replaced with the signed-in user's
// first name when available, otherwise stripped out gracefully.
export const MEGSY_TYPING_PHRASES: string[] = [
  "I'm right here, {name}",
  "Take your time, {name}",
  "Show me what you've got, {name}",
  "Tell me everything, {name}",
  "I'm listening, {name}",
  "Let's build something great, {name}",
  "Ready when you are, {name}",
  "What's on your mind, {name}?",
  "Hit me with it, {name}",
  "I've got you, {name}",
  "All ears, {name}",
  "Keep going, {name}",
  "Bring the idea to life, {name}",
  "Say the word, {name}",
  "Let's make magic, {name}",
  "I'm with you, {name}",
  "You set the direction, {name}",
  "Type away, {name}",
  "Don't hold back, {name}",
  "I love where this is going, {name}",
  "Share the vision, {name}",
  "We'll figure it out, {name}",
  "Trust the process, {name}",
  "Slow and steady, {name}",
  "Big or small, I'm in",
  "No idea is too wild",
  "I'll make it shine",
  "I'm fully focused",
  "Brain warmed up",
  "Pen in hand",
  "Eyes on your words",
  "Locked in",
  "Curiosity is on",
  "Let's go",
  "I'm hyped",
  "Drop it when ready",
  "Spill the idea",
  "Tell me more",
  "I'm taking notes",
  "Ooh, interesting",
  "Keep that energy",
  "I see where you're heading",
  "Love this direction",
  "Almost there",
  "Make it count",
  "I'll handle the rest",
  "You write, I'll build",
  "Words first, results next",
  "I'm patient",
  "No pressure",
  "Whenever you're ready",
  "Even rough drafts work",
  "Start anywhere",
  "Just a sentence is enough",
  "Try one line and we'll grow it",
  "I can work with anything",
  "I adapt to your style",
  "Lead the way",
  "I'll follow your lead",
  "Tell me the goal",
  "Paint the picture",
  "Sketch it in words",
  "I'll fill in the gaps",
  "Give me the gist",
  "Headline first, details later",
  "A keyword works too",
  "Even one word helps",
  "Type, then breathe",
  "I'm not going anywhere",
  "Take a breath, {name}",
  "Whenever, {name}",
  "Your move, {name}",
  "Calm and steady, {name}",
  "Let's keep it simple",
  "Clarity wins",
  "Short prompts are powerful",
  "Long prompts are fine too",
  "Whatever feels right",
  "I'll keep up",
  "I'm fast on the draw",
  "I'm ready to dive in",
  "Pick a topic, any topic",
  "Surprise me",
  "Make my day",
  "I love a good challenge",
  "Bring the heat",
  "I'm warmed up",
  "Coffee is brewing",
  "Engines running",
  "Hands on the keyboard",
  "I'll match your tone",
  "Casual or formal, your call",
  "English, Arabic, anything",
  "Switch languages anytime",
  "I'm flexible",
  "Reframe it however you want",
  "Try a different angle",
  "Or stick with this one",
  "I'm here for both",
  "Confidence loaded",
  "Imagination engaged",
  "Word factory online",
  "Story mode ready",
  "Ideas welcome",
  "Drafts welcome",
  "Half-thoughts welcome",
  "Questions welcome",
  "Rants welcome",
  "Even a hello works, {name}",
  "Glad you're here, {name}",
  "Good to see you again, {name}",
  "Let's pick up where we left off, {name}",
  "What are we making today, {name}?",
  "What can I do for you, {name}?",
  "Set the scene, {name}",
  "Frame the problem, {name}",
  "Name the goal, {name}",
  "I'll meet you halfway",
  "Two minds, one task",
  "Together we move faster",
  "Step by step",
  "Hand in hand",
  "Side by side",
  "We've got this",
  "I'll keep it tight",
  "I'll keep it clear",
  "I'll keep it useful",
  "I'll keep it kind",
  "I'll be honest",
  "I'll be precise",
  "I'll be quick",
  "I'll be thorough",
  "Whichever you prefer",
  "Tell me how deep to go",
  "Shallow scan or deep dive?",
  "Quick answer or full plan?",
  "Bullet points or paragraphs?",
  "Code or words?",
  "Plain or polished?",
  "Draft or final?",
  "Outline or full text?",
  "Just ask",
  "I'm only a prompt away",
  "Press send when ready",
  "I'll do my best work for you, {name}",
  "Your ideas matter, {name}",
  "Nothing is too small to ask",
  "Curious to see what you'll write",
  "Excited to help",
  "Glad we're doing this together",
  "Thanks for trusting me",
  "I appreciate you, {name}",
  "Let's make this one count",
  "Quality over speed",
  "But speed is fine too",
  "Whichever feels right",
  "I'll keep it grounded",
  "I'll keep it real",
  "I'll keep it focused",
  "I'll keep it on-brief",
  "On-brief and on-time",
  "Watching the cursor",
  "Reading every word",
  "Holding the thread",
  "Following along",
  "Picking up the pattern",
  "Mapping it out",
  "Plotting the plan",
  "Sketching the shape",
  "Drawing the outline",
  "Drafting silently",
  "Thinking ahead",
  "Lining up ideas",
  "Saving space for surprises",
  "I'm patient with edits",
  "Rewrite as often as you like",
  "Iterate freely",
  "We can pivot anytime",
  "Change direction whenever",
  "I'll adjust",
  "I'll keep up",
  "I'll catch up",
  "I'll roll with it",
  "I'll learn from you, {name}",
  "Every prompt teaches me something",
  "You're shaping how I help",
  "Lead with intent",
  "Lead with curiosity",
  "Lead with playfulness",
  "Whatever feels natural",
  "I'm not judging",
  "I'm just helping",
  "Quiet confidence",
  "Quiet focus",
  "Quiet effort",
  "Loud results",
  "Big payoff incoming",
  "Stay with me, {name}",
  "Hold the thread, {name}",
  "Trust your gut, {name}",
  "Trust the words, {name}",
  "Send it when ready, {name}",
  "I'll be right here, {name}",
  "Same place, same friend, {name}",
  "Ready to make something, {name}?",
  "Let's begin, {name}",
  "From scratch is fine",
  "From scraps is fine",
  "From a whole plan is fine",
  "From a single word is fine",
  "I work with all of it",
  "Anything you've got",
  "Whatever shape it's in",
  "We'll smooth it out",
  "We'll sharpen it up",
  "We'll bring it to life",
  "We'll make it land",
  "We'll make it sing",
  "We'll make it yours",
];

export function pickMegsyPhrase(name?: string | null): string {
  const phrase = MEGSY_TYPING_PHRASES[Math.floor(Math.random() * MEGSY_TYPING_PHRASES.length)];
  const clean = (name || "").trim().split(/\s+/)[0] || "";
  if (!phrase.includes("{name}")) return phrase;
  if (clean) return phrase.replace(/\{name\}/g, clean);
  // Strip a trailing ", {name}" gracefully if no name available.
  return phrase
    .replace(/,\s*\{name\}\??/g, "")
    .replace(/\{name\}/g, "friend")
    .trim();
}
