/** @doc Catalog of ready-made API apps.
 *
 *  Every entry is a public REST service with a self-serve key: the user pastes
 *  their own key once and the listed tools become usable from chat right away.
 */
import type { ApiApp } from "./types";

export const API_APPS: ApiApp[] = [
  {
    id: "openweathermap",
    name: "OpenWeatherMap",
    category: "weather",
    description: "Current weather and forecasts by city",
    docsUrl: "https://openweathermap.org/api",
    keyUrl: "https://home.openweathermap.org/api_keys",
    baseUrl: "https://api.openweathermap.org/data/2.5",
    auth: { type: "query", name: "appid" },
    logo: "https://cdn.simpleicons.org/openweathermap",
    tools: [
      {
        name: "Current weather",
        description: "Weather right now for a city",
        method: "GET",
        path: "/weather",
        params: [
          { name: "q", in: "query", required: true, description: "City name" },
          { name: "units", in: "query", required: false, description: "metric or imperial" },
        ],
      },
      {
        name: "5 day forecast",
        description: "3-hour forecast for five days",
        method: "GET",
        path: "/forecast",
        params: [{ name: "q", in: "query", required: true, description: "City name" }],
      },
    ],
  },
  {
    id: "newsapi",
    name: "NewsAPI",
    category: "data",
    description: "Live news articles worldwide",
    docsUrl: "https://newsapi.org/docs",
    keyUrl: "https://newsapi.org/register",
    baseUrl: "https://newsapi.org/v2",
    auth: { type: "header", name: "X-Api-Key" },
    logo: "https://newsapi.org/favicon.ico",
    tools: [
      {
        name: "Search articles",
        description: "Search all articles by keyword",
        method: "GET",
        path: "/everything",
        params: [{ name: "q", in: "query", required: true, description: "Search keywords" }],
      },
      {
        name: "Top headlines",
        description: "Breaking headlines by country or category",
        method: "GET",
        path: "/top-headlines",
        params: [
          { name: "country", in: "query", required: false, description: "2-letter country code" },
          { name: "category", in: "query", required: false, description: "News category" },
        ],
      },
    ],
  },
  {
    id: "tmdb",
    name: "TMDB",
    category: "media",
    description: "Movie and TV metadata, cast and images",
    docsUrl: "https://developer.themoviedb.org/docs",
    keyUrl: "https://www.themoviedb.org/settings/api",
    baseUrl: "https://api.themoviedb.org/3",
    auth: { type: "query", name: "api_key" },
    logo: "https://cdn.simpleicons.org/themoviedatabase",
    tools: [
      {
        name: "Search movie",
        description: "Find movies by title",
        method: "GET",
        path: "/search/movie",
        params: [{ name: "query", in: "query", required: true, description: "Movie title" }],
      },
      {
        name: "Movie details",
        description: "Full details for one movie",
        method: "GET",
        path: "/movie/{movie_id}",
        params: [{ name: "movie_id", in: "path", required: true, description: "Movie ID" }],
      },
      {
        name: "Trending",
        description: "What is trending this week",
        method: "GET",
        path: "/trending/movie/week",
        params: [],
      },
    ],
  },
  {
    id: "unsplash",
    name: "Unsplash",
    category: "media",
    description: "Free high-quality stock photos",
    docsUrl: "https://unsplash.com/documentation",
    keyUrl: "https://unsplash.com/oauth/applications",
    baseUrl: "https://api.unsplash.com",
    auth: { type: "header", name: "Authorization", prefix: "Client-ID " },
    logo: "https://cdn.simpleicons.org/unsplash",
    tools: [
      {
        name: "Search photos",
        description: "Search photos by keyword",
        method: "GET",
        path: "/search/photos",
        params: [{ name: "query", in: "query", required: true, description: "Search term" }],
      },
      {
        name: "Random photo",
        description: "One random photo, optionally by topic",
        method: "GET",
        path: "/photos/random",
        params: [{ name: "query", in: "query", required: false, description: "Filter keyword" }],
      },
    ],
  },
  {
    id: "opencage",
    name: "OpenCage",
    category: "data",
    description: "Geocoding for addresses and coordinates",
    docsUrl: "https://opencagedata.com/api",
    keyUrl: "https://opencagedata.com/users/sign_up",
    baseUrl: "https://api.opencagedata.com/geocode/v1",
    auth: { type: "query", name: "key" },
    logo: "https://opencagedata.com/favicon.ico",
    tools: [
      {
        name: "Geocode",
        description: "Turn an address into coordinates",
        method: "GET",
        path: "/json",
        params: [{ name: "q", in: "query", required: true, description: "Address or place" }],
      },
    ],
  },
  {
    id: "exchangerate",
    name: "ExchangeRate",
    category: "finance",
    description: "Live currency rates and conversion",
    docsUrl: "https://www.exchangerate-api.com/docs/standard-requests",
    keyUrl: "https://app.exchangerate-api.com/sign-up",
    baseUrl: "https://v6.exchangerate-api.com/v6",
    auth: { type: "path", name: "key" },
    logo: "https://www.exchangerate-api.com/favicon.ico",
    tools: [
      {
        name: "Latest rates",
        description: "All rates for one base currency",
        method: "GET",
        path: "/{key}/latest/{base_code}",
        params: [
          { name: "base_code", in: "path", required: true, description: "Currency code, e.g. USD" },
        ],
      },
      {
        name: "Convert amount",
        description: "Convert between two currencies",
        method: "GET",
        path: "/{key}/pair/{base}/{target}/{amount}",
        params: [
          { name: "base", in: "path", required: true, description: "From currency" },
          { name: "target", in: "path", required: true, description: "To currency" },
          { name: "amount", in: "path", required: true, description: "Amount to convert" },
        ],
      },
    ],
  },
  {
    id: "alphavantage",
    name: "Alpha Vantage",
    category: "finance",
    description: "Stock, forex and crypto market data",
    docsUrl: "https://www.alphavantage.co/documentation",
    keyUrl: "https://www.alphavantage.co/support/#api-key",
    baseUrl: "https://www.alphavantage.co",
    auth: { type: "query", name: "apikey" },
    logo: "https://www.alphavantage.co/favicon.ico",
    tools: [
      {
        name: "Price quote",
        description: "Latest quote for a ticker",
        method: "GET",
        path: "/query",
        params: [
          { name: "function", in: "query", required: true, description: "Use GLOBAL_QUOTE" },
          { name: "symbol", in: "query", required: true, description: "Ticker symbol" },
        ],
      },
      {
        name: "Daily history",
        description: "Daily open/high/low/close series",
        method: "GET",
        path: "/query",
        params: [
          { name: "function", in: "query", required: true, description: "Use TIME_SERIES_DAILY" },
          { name: "symbol", in: "query", required: true, description: "Ticker symbol" },
        ],
      },
    ],
  },
  {
    id: "coinmarketcap",
    name: "CoinMarketCap",
    category: "finance",
    description: "Crypto prices, market cap and ranking",
    docsUrl: "https://coinmarketcap.com/api/documentation/v1",
    keyUrl: "https://pro.coinmarketcap.com/signup",
    baseUrl: "https://pro-api.coinmarketcap.com/v1",
    auth: { type: "header", name: "X-CMC_PRO_API_KEY" },
    logo: "https://cdn.simpleicons.org/coinmarketcap",
    tools: [
      {
        name: "Top listings",
        description: "Market ranking of coins",
        method: "GET",
        path: "/cryptocurrency/listings/latest",
        params: [{ name: "limit", in: "query", required: false, description: "How many results" }],
      },
      {
        name: "Coin quote",
        description: "Latest price for a symbol",
        method: "GET",
        path: "/cryptocurrency/quotes/latest",
        params: [{ name: "symbol", in: "query", required: true, description: "Symbol, e.g. BTC" }],
      },
    ],
  },
  {
    id: "giphy",
    name: "GIPHY",
    category: "media",
    description: "Search and trending GIFs",
    docsUrl: "https://developers.giphy.com/docs/api",
    keyUrl: "https://developers.giphy.com/dashboard",
    baseUrl: "https://api.giphy.com/v1/gifs",
    auth: { type: "query", name: "api_key" },
    logo: "https://cdn.simpleicons.org/giphy",
    tools: [
      {
        name: "Search GIFs",
        description: "Find GIFs by keyword",
        method: "GET",
        path: "/search",
        params: [{ name: "q", in: "query", required: true, description: "Search term" }],
      },
      {
        name: "Trending GIFs",
        description: "What is trending now",
        method: "GET",
        path: "/trending",
        params: [{ name: "limit", in: "query", required: false, description: "How many results" }],
      },
    ],
  },
  {
    id: "nasa",
    name: "NASA",
    category: "data",
    description: "Space imagery and Mars rover photos",
    docsUrl: "https://api.nasa.gov",
    keyUrl: "https://api.nasa.gov",
    baseUrl: "https://api.nasa.gov",
    auth: { type: "query", name: "api_key" },
    logo: "https://cdn.simpleicons.org/nasa",
    tools: [
      {
        name: "Picture of the day",
        description: "Today's featured space image",
        method: "GET",
        path: "/planetary/apod",
        params: [{ name: "date", in: "query", required: false, description: "YYYY-MM-DD" }],
      },
      {
        name: "Mars photos",
        description: "Photos taken by the Curiosity rover",
        method: "GET",
        path: "/mars-photos/api/v1/rovers/curiosity/photos",
        params: [{ name: "sol", in: "query", required: true, description: "Martian day number" }],
      },
    ],
  },
  {
    id: "ipgeolocation",
    name: "IP Geolocation",
    category: "data",
    description: "Location details for an IP address",
    docsUrl: "https://ipgeolocation.io/documentation/ip-geolocation-api.html",
    keyUrl: "https://app.ipgeolocation.io/signup",
    baseUrl: "https://api.ipgeolocation.io",
    auth: { type: "query", name: "apiKey" },
    logo: "https://ipgeolocation.io/favicon.ico",
    tools: [
      {
        name: "IP lookup",
        description: "Country, city and timezone of an IP",
        method: "GET",
        path: "/ipgeo",
        params: [{ name: "ip", in: "query", required: false, description: "IP address" }],
      },
    ],
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    category: "comms",
    description: "Send transactional email",
    docsUrl: "https://www.twilio.com/docs/sendgrid/api-reference/mail-send/mail-send",
    keyUrl: "https://app.sendgrid.com/settings/api_keys",
    baseUrl: "https://api.sendgrid.com/v3",
    auth: { type: "header", name: "Authorization", prefix: "Bearer " },
    logo: "https://cdn.simpleicons.org/sendgrid",
    tools: [
      {
        name: "Send email",
        description: "Send one email message",
        method: "POST",
        path: "/mail/send",
        params: [
          { name: "personalizations", in: "body", required: true, description: "Recipients" },
          { name: "from", in: "body", required: true, description: "Sender address object" },
          { name: "subject", in: "body", required: true, description: "Subject line" },
          { name: "content", in: "body", required: true, description: "Message body parts" },
        ],
      },
    ],
  },
  {
    id: "deepl",
    name: "DeepL",
    category: "data",
    description: "Translate text between languages",
    docsUrl: "https://developers.deepl.com/docs/api-reference/translate",
    keyUrl: "https://www.deepl.com/pro-api",
    baseUrl: "https://api-free.deepl.com/v2",
    auth: { type: "header", name: "Authorization", prefix: "DeepL-Auth-Key " },
    logo: "https://cdn.simpleicons.org/deepl",
    tools: [
      {
        name: "Translate text",
        description: "Translate into a target language",
        method: "POST",
        path: "/translate",
        params: [
          { name: "text", in: "body", required: true, description: "Array of strings" },
          { name: "target_lang", in: "body", required: true, description: "Language code, e.g. AR" },
        ],
      },
    ],
  },
  {
    id: "serpapi",
    name: "SerpApi",
    category: "search",
    description: "Search engine results as clean JSON",
    docsUrl: "https://serpapi.com/search-api",
    keyUrl: "https://serpapi.com/users/sign_up",
    baseUrl: "https://serpapi.com",
    auth: { type: "query", name: "api_key" },
    logo: "https://serpapi.com/favicon.ico",
    tools: [
      {
        name: "Search",
        description: "Run a search and get results",
        method: "GET",
        path: "/search",
        params: [
          { name: "q", in: "query", required: true, description: "Search query" },
          { name: "engine", in: "query", required: false, description: "Engine, default google" },
        ],
      },
    ],
  },
  {
    id: "api-football",
    name: "API-Football",
    category: "data",
    description: "Football fixtures, scores and standings",
    docsUrl: "https://www.api-football.com/documentation-v3",
    keyUrl: "https://dashboard.api-football.com/register",
    baseUrl: "https://v3.football.api-sports.io",
    auth: { type: "header", name: "x-apisports-key" },
    logo: "https://www.api-football.com/favicon.ico",
    tools: [
      {
        name: "Fixtures",
        description: "Matches by date or league",
        method: "GET",
        path: "/fixtures",
        params: [
          { name: "date", in: "query", required: false, description: "YYYY-MM-DD" },
          { name: "league", in: "query", required: false, description: "League ID" },
        ],
      },
      {
        name: "Standings",
        description: "League table for a season",
        method: "GET",
        path: "/standings",
        params: [
          { name: "league", in: "query", required: true, description: "League ID" },
          { name: "season", in: "query", required: true, description: "Season year" },
        ],
      },
    ],
  },
  {
    id: "tinyurl",
    name: "TinyURL",
    category: "dev",
    description: "Shorten long links",
    docsUrl: "https://tinyurl.com/app/dev",
    keyUrl: "https://tinyurl.com/app/dev",
    baseUrl: "https://api.tinyurl.com",
    auth: { type: "header", name: "Authorization", prefix: "Bearer " },
    logo: "https://tinyurl.com/favicon.ico",
    tools: [
      {
        name: "Shorten link",
        description: "Create a short URL",
        method: "POST",
        path: "/create",
        params: [{ name: "url", in: "body", required: true, description: "Long URL" }],
      },
    ],
  },
  {
    id: "currents",
    name: "Currents",
    category: "data",
    description: "Recent news by keyword or category",
    docsUrl: "https://currentsapi.services/en/docs/",
    keyUrl: "https://currentsapi.services/en/register",
    baseUrl: "https://api.currentsapi.services/v1",
    auth: { type: "query", name: "apiKey" },
    logo: "https://currentsapi.services/favicon.ico",
    tools: [
      {
        name: "Search news",
        description: "Search recent articles",
        method: "GET",
        path: "/search",
        params: [{ name: "keywords", in: "query", required: true, description: "Search keywords" }],
      },
      {
        name: "Latest news",
        description: "Newest articles by language",
        method: "GET",
        path: "/latest-news",
        params: [
          { name: "language", in: "query", required: false, description: "Language code" },
        ],
      },
    ],
  },
  {
    id: "spoonacular",
    name: "Spoonacular",
    category: "data",
    description: "Recipes and nutrition information",
    docsUrl: "https://spoonacular.com/food-api/docs",
    keyUrl: "https://spoonacular.com/food-api/console#Dashboard",
    baseUrl: "https://api.spoonacular.com",
    auth: { type: "query", name: "apiKey" },
    logo: "https://spoonacular.com/favicon.ico",
    tools: [
      {
        name: "Search recipes",
        description: "Find recipes by keyword",
        method: "GET",
        path: "/recipes/complexSearch",
        params: [{ name: "query", in: "query", required: true, description: "Recipe search term" }],
      },
      {
        name: "Recipe details",
        description: "Ingredients and steps for a recipe",
        method: "GET",
        path: "/recipes/{id}/information",
        params: [{ name: "id", in: "path", required: true, description: "Recipe ID" }],
      },
    ],
  },
  {
    id: "airtable",
    name: "Airtable",
    category: "dev",
    description: "Read and add records in your bases",
    docsUrl: "https://airtable.com/developers/web/api/introduction",
    keyUrl: "https://airtable.com/create/tokens",
    baseUrl: "https://api.airtable.com/v0",
    auth: { type: "header", name: "Authorization", prefix: "Bearer " },
    logo: "https://cdn.simpleicons.org/airtable",
    tools: [
      {
        name: "List records",
        description: "Read rows from a table",
        method: "GET",
        path: "/{baseId}/{tableName}",
        params: [
          { name: "baseId", in: "path", required: true, description: "Base ID" },
          { name: "tableName", in: "path", required: true, description: "Table name" },
        ],
      },
    ],
  },
  {
    id: "resend",
    name: "Resend",
    category: "comms",
    description: "Send email from your own domain",
    docsUrl: "https://resend.com/docs/api-reference/emails/send-email",
    keyUrl: "https://resend.com/api-keys",
    baseUrl: "https://api.resend.com",
    auth: { type: "header", name: "Authorization", prefix: "Bearer " },
    logo: "https://cdn.simpleicons.org/resend",
    tools: [
      {
        name: "Send email",
        description: "Send one email message",
        method: "POST",
        path: "/emails",
        params: [
          { name: "from", in: "body", required: true, description: "Sender address" },
          { name: "to", in: "body", required: true, description: "Recipient address" },
          { name: "subject", in: "body", required: true, description: "Subject line" },
          { name: "html", in: "body", required: false, description: "HTML body" },
        ],
      },
    ],
  },
  {
    id: "notion",
    name: "Notion",
    category: "dev",
    description: "Search and read your Notion pages",
    docsUrl: "https://developers.notion.com/reference/intro",
    keyUrl: "https://www.notion.so/my-integrations",
    baseUrl: "https://api.notion.com/v1",
    auth: { type: "header", name: "Authorization", prefix: "Bearer " },
    logo: "https://cdn.simpleicons.org/notion",
    tools: [
      {
        name: "Search",
        description: "Search pages and databases",
        method: "POST",
        path: "/search",
        params: [{ name: "query", in: "body", required: false, description: "Search text" }],
      },
    ],
  },
  {
    id: "weatherapi",
    name: "WeatherAPI",
    category: "weather",
    description: "Forecast, history and air quality",
    docsUrl: "https://www.weatherapi.com/docs/",
    keyUrl: "https://www.weatherapi.com/signup.aspx",
    baseUrl: "https://api.weatherapi.com/v1",
    auth: { type: "query", name: "key" },
    logo: "https://www.weatherapi.com/favicon.ico",
    tools: [
      {
        name: "Forecast",
        description: "Multi-day forecast for a place",
        method: "GET",
        path: "/forecast.json",
        params: [
          { name: "q", in: "query", required: true, description: "City or coordinates" },
          { name: "days", in: "query", required: false, description: "Number of days" },
        ],
      },
    ],
  },
];

import { MANUS_APPS } from "./manus";
import { loadNangoApps, loadedNangoApps } from "./nango.generated";

/** Any connectable app: curated catalog, the Manus line-up, or the wider registry. */
export const findApiApp = (id: string) =>
  API_APPS.find((a) => a.id === id) ??
  MANUS_APPS.find((a) => a.id === id) ??
  loadedNangoApps().find((a) => a.id === id);

/** Same lookup, but pulls the lazy Nango registry in when needed. */
export const findApiAppAsync = async (id: string) =>
  API_APPS.find((a) => a.id === id) ??
  MANUS_APPS.find((a) => a.id === id) ??
  (await loadNangoApps()).find((a) => a.id === id);
