/** @doc The connector line-up Manus ships, rebuilt as API-key apps.
 *
 *  Source: Manus API docs → "Available connectors" (open.manus.ai/docs/v2/connectors).
 *  Manus authorises these over OAuth; here each one is wired to its public REST
 *  API so the user pastes their own key once and the listed endpoints become
 *  callable from chat. Order follows the Manus list, most used first.
 */
import { serviceLogo } from "./logos.generated";
import type { ApiApp, ApiAppCategory, ApiAppCredential } from "./types";

type Seed = {
  id: string;
  name: string;
  category: ApiAppCategory;
  description: string;
  docs: string;
  key: string;
  base: string;
  /** header name, or ["query", name] / ["header", name, prefix] */
  auth: { type: "header" | "query"; name: string; prefix?: string };
  icon?: string;
  tools: Array<{
    name: string;
    description: string;
    method: "GET" | "POST";
    path: string;
    params?: Array<{ name: string; in: "query" | "path" | "body"; required?: boolean; description: string }>;
  }>;
};

const bearer = { type: "header" as const, name: "Authorization", prefix: "Bearer " };

const SEEDS: Seed[] = [
  {
    id: "slack",
    name: "Slack",
    category: "comms",
    description: "Send messages and read channels",
    docs: "https://api.slack.com/methods",
    key: "https://api.slack.com/apps",
    base: "https://slack.com/api",
    auth: bearer,
    tools: [
      {
        name: "Send message",
        description: "Post a message to a channel",
        method: "POST",
        path: "/chat.postMessage",
        params: [
          { name: "channel", in: "body", required: true, description: "Channel id or name" },
          { name: "text", in: "body", required: true, description: "Message text" },
        ],
      },
      { name: "List channels", description: "Channels in the workspace", method: "GET", path: "/conversations.list" },
    ],
  },
  {
    id: "notion",
    name: "Notion",
    category: "data",
    description: "Search pages and create content",
    docs: "https://developers.notion.com/reference",
    key: "https://www.notion.so/my-integrations",
    base: "https://api.notion.com/v1",
    auth: bearer,
    tools: [
      {
        name: "Search",
        description: "Search pages and databases",
        method: "POST",
        path: "/search",
        params: [{ name: "query", in: "body", required: true, description: "Search text" }],
      },
      {
        name: "Get page",
        description: "Read a page by id",
        method: "GET",
        path: "/pages/{page_id}",
        params: [{ name: "page_id", in: "path", required: true, description: "Page id" }],
      },
    ],
  },
  {
    id: "zapier",
    name: "Zapier",
    category: "data",
    description: "Trigger Zaps across thousands of apps",
    docs: "https://docs.zapier.com/platform/build/nla-api",
    key: "https://nla.zapier.com/credentials/",
    base: "https://nla.zapier.com/api/v1",
    auth: { type: "header", name: "X-API-Key" },
    tools: [
      { name: "List actions", description: "Actions you exposed to the assistant", method: "GET", path: "/exposed/" },
    ],
  },
  {
    id: "asana",
    name: "Asana",
    category: "data",
    description: "Tasks and projects",
    docs: "https://developers.asana.com/reference",
    key: "https://app.asana.com/0/my-apps",
    base: "https://app.asana.com/api/1.0",
    auth: bearer,
    tools: [
      { name: "My tasks", description: "Tasks assigned to you", method: "GET", path: "/users/me" },
      {
        name: "List projects",
        description: "Projects in a workspace",
        method: "GET",
        path: "/projects",
        params: [{ name: "workspace", in: "query", description: "Workspace id" }],
      },
    ],
  },
  {
    id: "monday",
    name: "monday.com",
    category: "data",
    description: "Boards, items and updates",
    docs: "https://developer.monday.com/api-reference",
    key: "https://monday.com/developers/v2",
    base: "https://api.monday.com/v2",
    auth: { type: "header", name: "Authorization" },
    tools: [
      {
        name: "Run query",
        description: "GraphQL query against your boards",
        method: "POST",
        path: "",
        params: [{ name: "query", in: "body", required: true, description: "GraphQL query" }],
      },
    ],
  },
  {
    id: "make",
    name: "Make",
    category: "data",
    description: "Run and monitor scenarios",
    docs: "https://developers.make.com/api-documentation",
    key: "https://www.make.com/en/help/apps/api",
    base: "https://eu1.make.com/api/v2",
    auth: { type: "header", name: "Authorization", prefix: "Token " },
    tools: [
      {
        name: "List scenarios",
        description: "Scenarios in a team",
        method: "GET",
        path: "/scenarios",
        params: [{ name: "teamId", in: "query", description: "Team id" }],
      },
    ],
  },
  {
    id: "linear",
    name: "Linear",
    category: "dev",
    description: "Issues, projects and cycles",
    docs: "https://developers.linear.app/docs",
    key: "https://linear.app/settings/api",
    base: "https://api.linear.app",
    auth: { type: "header", name: "Authorization" },
    tools: [
      {
        name: "Run query",
        description: "GraphQL query for issues and teams",
        method: "POST",
        path: "/graphql",
        params: [{ name: "query", in: "body", required: true, description: "GraphQL query" }],
      },
    ],
  },
  {
    id: "atlassian",
    name: "Atlassian",
    category: "dev",
    description: "Jira issues and Confluence pages",
    docs: "https://developer.atlassian.com/cloud/jira/platform/rest/v3/",
    key: "https://id.atlassian.com/manage-profile/security/api-tokens",
    base: "https://api.atlassian.com/ex/jira",
    auth: bearer,
    tools: [
      { name: "Accessible sites", description: "Sites your token can reach", method: "GET", path: "/oauth/token/accessible-resources" },
    ],
  },
  {
    id: "clickup",
    name: "ClickUp",
    category: "data",
    description: "Tasks, lists and spaces",
    docs: "https://developer.clickup.com/reference",
    key: "https://app.clickup.com/settings/apps",
    base: "https://api.clickup.com/api/v2",
    auth: { type: "header", name: "Authorization" },
    tools: [
      { name: "My teams", description: "Workspaces you belong to", method: "GET", path: "/team" },
      {
        name: "List tasks",
        description: "Tasks in a list",
        method: "GET",
        path: "/list/{list_id}/task",
        params: [{ name: "list_id", in: "path", required: true, description: "List id" }],
      },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    category: "ai",
    description: "GPT models, images and embeddings",
    docs: "https://platform.openai.com/docs/api-reference",
    key: "https://platform.openai.com/api-keys",
    base: "https://api.openai.com/v1",
    auth: bearer,
    tools: [
      { name: "List models", description: "Models available to your key", method: "GET", path: "/models" },
      {
        name: "Chat completion",
        description: "Generate a response",
        method: "POST",
        path: "/chat/completions",
        params: [
          { name: "model", in: "body", required: true, description: "Model id" },
          { name: "messages", in: "body", required: true, description: "Chat messages" },
        ],
      },
    ],
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "dev",
    description: "Projects, database and auth",
    docs: "https://supabase.com/docs/reference/api",
    key: "https://supabase.com/dashboard/account/tokens",
    base: "https://api.supabase.com/v1",
    auth: bearer,
    tools: [{ name: "List projects", description: "Your Supabase projects", method: "GET", path: "/projects" }],
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "dev",
    description: "Deployments and projects",
    docs: "https://vercel.com/docs/rest-api",
    key: "https://vercel.com/account/tokens",
    base: "https://api.vercel.com",
    auth: bearer,
    tools: [
      { name: "List projects", description: "Projects in your account", method: "GET", path: "/v9/projects" },
      { name: "List deployments", description: "Recent deployments", method: "GET", path: "/v6/deployments" },
    ],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    category: "ai",
    description: "Claude models",
    docs: "https://docs.anthropic.com/en/api",
    key: "https://console.anthropic.com/settings/keys",
    base: "https://api.anthropic.com/v1",
    auth: { type: "header", name: "x-api-key" },
    tools: [
      { name: "List models", description: "Claude models for your key", method: "GET", path: "/models" },
      {
        name: "Create message",
        description: "Ask Claude",
        method: "POST",
        path: "/messages",
        params: [
          { name: "model", in: "body", required: true, description: "Model id" },
          { name: "messages", in: "body", required: true, description: "Chat messages" },
          { name: "max_tokens", in: "body", required: true, description: "Token limit" },
        ],
      },
    ],
  },
  {
    id: "neon",
    name: "Neon",
    category: "dev",
    description: "Serverless Postgres projects",
    docs: "https://api-docs.neon.tech/reference/getting-started-with-neon-api",
    key: "https://console.neon.tech/app/settings/api-keys",
    base: "https://console.neon.tech/api/v2",
    auth: bearer,
    tools: [{ name: "List projects", description: "Your Neon projects", method: "GET", path: "/projects" }],
  },
  {
    id: "gemini",
    name: "Google Gemini",
    category: "ai",
    description: "Gemini models and embeddings",
    docs: "https://ai.google.dev/api",
    key: "https://aistudio.google.com/app/apikey",
    base: "https://generativelanguage.googleapis.com/v1beta",
    auth: { type: "header", name: "x-goog-api-key" },
    tools: [
      { name: "List models", description: "Gemini models", method: "GET", path: "/models" },
      {
        name: "Generate content",
        description: "Prompt a Gemini model",
        method: "POST",
        path: "/models/gemini-2.5-flash:generateContent",
        params: [{ name: "contents", in: "body", required: true, description: "Prompt contents" }],
      },
    ],
  },
  {
    id: "prisma-postgres",
    name: "Prisma Postgres",
    category: "dev",
    description: "Managed Postgres projects",
    docs: "https://www.prisma.io/docs/postgres",
    key: "https://console.prisma.io/",
    base: "https://api.prisma.io/v1",
    auth: bearer,
    tools: [{ name: "List projects", description: "Prisma Postgres projects", method: "GET", path: "/projects" }],
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "dev",
    description: "Errors, issues and releases",
    docs: "https://docs.sentry.io/api/",
    key: "https://sentry.io/settings/account/api/auth-tokens/",
    base: "https://sentry.io/api/0",
    auth: bearer,
    tools: [
      { name: "List projects", description: "Projects you can see", method: "GET", path: "/projects/" },
      {
        name: "List issues",
        description: "Unresolved issues for a project",
        method: "GET",
        path: "/projects/{organization_slug}/{project_slug}/issues/",
        params: [
          { name: "organization_slug", in: "path", required: true, description: "Org slug" },
          { name: "project_slug", in: "path", required: true, description: "Project slug" },
        ],
      },
    ],
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    category: "ai",
    description: "Models, datasets and inference",
    docs: "https://huggingface.co/docs/hub/api",
    key: "https://huggingface.co/settings/tokens",
    base: "https://huggingface.co/api",
    auth: bearer,
    tools: [
      {
        name: "Search models",
        description: "Find models on the Hub",
        method: "GET",
        path: "/models",
        params: [{ name: "search", in: "query", description: "Search text" }],
      },
      {
        name: "Search datasets",
        description: "Find datasets on the Hub",
        method: "GET",
        path: "/datasets",
        params: [{ name: "search", in: "query", description: "Search text" }],
      },
    ],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    category: "ai",
    description: "Answers with live web sources",
    docs: "https://docs.perplexity.ai/api-reference",
    key: "https://www.perplexity.ai/settings/api",
    base: "https://api.perplexity.ai",
    auth: bearer,
    tools: [
      {
        name: "Ask",
        description: "Answer a question with citations",
        method: "POST",
        path: "/chat/completions",
        params: [
          { name: "model", in: "body", required: true, description: "e.g. sonar" },
          { name: "messages", in: "body", required: true, description: "Chat messages" },
        ],
      },
    ],
  },
  {
    id: "cohere",
    name: "Cohere",
    category: "ai",
    description: "Chat, rerank and embeddings",
    docs: "https://docs.cohere.com/reference/about",
    key: "https://dashboard.cohere.com/api-keys",
    base: "https://api.cohere.com/v2",
    auth: bearer,
    tools: [
      {
        name: "Chat",
        description: "Generate a response",
        method: "POST",
        path: "/chat",
        params: [
          { name: "model", in: "body", required: true, description: "Model id" },
          { name: "messages", in: "body", required: true, description: "Chat messages" },
        ],
      },
    ],
  },
  {
    id: "hubspot",
    name: "HubSpot",
    category: "data",
    description: "CRM contacts, deals and companies",
    docs: "https://developers.hubspot.com/docs/api/overview",
    key: "https://app.hubspot.com/private-apps",
    base: "https://api.hubapi.com",
    auth: bearer,
    tools: [
      { name: "List contacts", description: "CRM contacts", method: "GET", path: "/crm/v3/objects/contacts" },
      { name: "List deals", description: "CRM deals", method: "GET", path: "/crm/v3/objects/deals" },
    ],
  },
  {
    id: "intercom",
    name: "Intercom",
    category: "comms",
    description: "Conversations and contacts",
    docs: "https://developers.intercom.com/docs/references/rest-api",
    key: "https://app.intercom.com/a/apps/_/developer-hub",
    base: "https://api.intercom.io",
    auth: bearer,
    tools: [
      { name: "List conversations", description: "Recent conversations", method: "GET", path: "/conversations" },
      { name: "List contacts", description: "Your contacts", method: "GET", path: "/contacts" },
    ],
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "media",
    description: "Text to speech and voices",
    docs: "https://elevenlabs.io/docs/api-reference",
    key: "https://elevenlabs.io/app/settings/api-keys",
    base: "https://api.elevenlabs.io/v1",
    auth: { type: "header", name: "xi-api-key" },
    tools: [
      { name: "List voices", description: "Voices on your account", method: "GET", path: "/voices" },
      {
        name: "Text to speech",
        description: "Generate audio from text",
        method: "POST",
        path: "/text-to-speech/{voice_id}",
        params: [
          { name: "voice_id", in: "path", required: true, description: "Voice id" },
          { name: "text", in: "body", required: true, description: "Text to speak" },
        ],
      },
    ],
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "finance",
    description: "Payments, customers and invoices",
    docs: "https://docs.stripe.com/api",
    key: "https://dashboard.stripe.com/apikeys",
    base: "https://api.stripe.com/v1",
    auth: bearer,
    tools: [
      { name: "List customers", description: "Recent customers", method: "GET", path: "/customers" },
      { name: "List payments", description: "Recent payment intents", method: "GET", path: "/payment_intents" },
      { name: "Balance", description: "Current account balance", method: "GET", path: "/balance" },
    ],
  },
  {
    id: "grok",
    name: "Grok",
    category: "ai",
    description: "xAI Grok models",
    docs: "https://docs.x.ai/api",
    key: "https://console.x.ai/",
    base: "https://api.x.ai/v1",
    auth: bearer,
    tools: [
      { name: "List models", description: "Grok models", method: "GET", path: "/models" },
      {
        name: "Chat completion",
        description: "Ask Grok",
        method: "POST",
        path: "/chat/completions",
        params: [
          { name: "model", in: "body", required: true, description: "Model id" },
          { name: "messages", in: "body", required: true, description: "Chat messages" },
        ],
      },
    ],
  },
  {
    id: "paypal",
    name: "PayPal for Business",
    category: "finance",
    description: "Orders, payouts and invoices",
    docs: "https://developer.paypal.com/api/rest/",
    key: "https://developer.paypal.com/dashboard/applications/live",
    base: "https://api-m.paypal.com/v1",
    auth: bearer,
    tools: [
      {
        name: "List invoices",
        description: "Invoices on the account",
        method: "GET",
        path: "/invoicing/invoices",
      },
      { name: "List transactions", description: "Transaction history", method: "GET", path: "/reporting/transactions" },
    ],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "ai",
    description: "One key for many LLM providers",
    docs: "https://openrouter.ai/docs",
    key: "https://openrouter.ai/keys",
    base: "https://openrouter.ai/api/v1",
    auth: bearer,
    tools: [
      { name: "List models", description: "Models you can call", method: "GET", path: "/models" },
      {
        name: "Chat completion",
        description: "Run a prompt on any model",
        method: "POST",
        path: "/chat/completions",
        params: [
          { name: "model", in: "body", required: true, description: "Model id" },
          { name: "messages", in: "body", required: true, description: "Chat messages" },
        ],
      },
    ],
  },
  {
    id: "revenuecat",
    name: "RevenueCat",
    category: "finance",
    description: "Subscriptions and app revenue",
    docs: "https://www.revenuecat.com/docs/api-v2",
    key: "https://app.revenuecat.com/",
    base: "https://api.revenuecat.com/v2",
    auth: bearer,
    tools: [{ name: "List projects", description: "Your RevenueCat projects", method: "GET", path: "/projects" }],
  },
  {
    id: "ahrefs",
    name: "Ahrefs",
    category: "data",
    description: "Backlinks, keywords and rankings",
    docs: "https://docs.ahrefs.com/docs/api",
    key: "https://app.ahrefs.com/api/profile",
    base: "https://api.ahrefs.com/v3",
    auth: bearer,
    tools: [
      {
        name: "Domain rating",
        description: "Domain rating for a site",
        method: "GET",
        path: "/site-explorer/domain-rating",
        params: [
          { name: "target", in: "query", required: true, description: "Domain" },
          { name: "date", in: "query", required: true, description: "YYYY-MM-DD" },
        ],
      },
    ],
  },
  {
    id: "close",
    name: "Close",
    category: "data",
    description: "Sales CRM leads and calls",
    docs: "https://developer.close.com/",
    key: "https://app.close.com/settings/api/",
    base: "https://api.close.com/api/v1",
    auth: bearer,
    tools: [
      { name: "List leads", description: "CRM leads", method: "GET", path: "/lead/" },
      { name: "List opportunities", description: "Open opportunities", method: "GET", path: "/opportunity/" },
    ],
  },
  {
    id: "xero",
    name: "Xero",
    category: "finance",
    description: "Accounting, invoices and contacts",
    docs: "https://developer.xero.com/documentation/api/accounting/overview",
    key: "https://developer.xero.com/app/manage",
    base: "https://api.xero.com/api.xro/2.0",
    auth: bearer,
    tools: [
      { name: "List invoices", description: "Accounting invoices", method: "GET", path: "/Invoices" },
      { name: "List contacts", description: "Accounting contacts", method: "GET", path: "/Contacts" },
    ],
  },
  {
    id: "similarweb",
    name: "Similarweb",
    category: "data",
    description: "Website traffic and audience data",
    docs: "https://developers.similarweb.com/",
    key: "https://account.similarweb.com/",
    base: "https://api.similarweb.com/v1",
    auth: { type: "query", name: "api_key" },
    tools: [
      {
        name: "Site visits",
        description: "Monthly visits for a domain",
        method: "GET",
        path: "/website/{domain}/total-traffic-and-engagement/visits",
        params: [{ name: "domain", in: "path", required: true, description: "Domain" }],
      },
    ],
  },
  {
    id: "dropbox",
    name: "Dropbox",
    category: "data",
    description: "Files and folders",
    docs: "https://www.dropbox.com/developers/documentation/http/overview",
    key: "https://www.dropbox.com/developers/apps",
    base: "https://api.dropboxapi.com/2",
    auth: bearer,
    tools: [
      {
        name: "List folder",
        description: "Files in a folder",
        method: "POST",
        path: "/files/list_folder",
        params: [{ name: "path", in: "body", required: true, description: "Folder path, empty for root" }],
      },
      {
        name: "Search files",
        description: "Search your Dropbox",
        method: "POST",
        path: "/files/search_v2",
        params: [{ name: "query", in: "body", required: true, description: "Search text" }],
      },
    ],
  },
  {
    id: "flux",
    name: "Flux",
    category: "media",
    description: "Image generation by Black Forest Labs",
    docs: "https://docs.bfl.ai/",
    key: "https://dashboard.bfl.ai/",
    base: "https://api.bfl.ai/v1",
    auth: { type: "header", name: "x-key" },
    tools: [
      {
        name: "Generate image",
        description: "Create an image from a prompt",
        method: "POST",
        path: "/flux-pro-1.1",
        params: [{ name: "prompt", in: "body", required: true, description: "Image prompt" }],
      },
    ],
  },
  {
    id: "airtable",
    name: "Airtable",
    category: "data",
    description: "Bases, tables and records",
    docs: "https://airtable.com/developers/web/api/introduction",
    key: "https://airtable.com/create/tokens",
    base: "https://api.airtable.com/v0",
    auth: bearer,
    tools: [
      { name: "List bases", description: "Bases your token can read", method: "GET", path: "/meta/bases" },
      {
        name: "List records",
        description: "Records in a table",
        method: "GET",
        path: "/{base_id}/{table}",
        params: [
          { name: "base_id", in: "path", required: true, description: "Base id" },
          { name: "table", in: "path", required: true, description: "Table name or id" },
        ],
      },
    ],
  },
  {
    id: "dify",
    name: "Dify",
    category: "ai",
    description: "Run your Dify AI apps",
    docs: "https://docs.dify.ai/guides/application-publishing/developing-with-apis",
    key: "https://cloud.dify.ai/apps",
    base: "https://api.dify.ai/v1",
    auth: bearer,
    tools: [
      {
        name: "Run workflow",
        description: "Execute a Dify workflow",
        method: "POST",
        path: "/workflows/run",
        params: [
          { name: "inputs", in: "body", required: true, description: "Workflow inputs" },
          { name: "user", in: "body", required: true, description: "End user id" },
        ],
      },
    ],
  },
  {
    id: "kling",
    name: "Kling",
    category: "media",
    description: "AI video generation",
    docs: "https://app.klingai.com/global/dev/document-api",
    key: "https://app.klingai.com/global/dev/api-key",
    base: "https://api-singapore.klingai.com/v1",
    auth: bearer,
    tools: [
      {
        name: "Text to video",
        description: "Generate a video from a prompt",
        method: "POST",
        path: "/videos/text2video",
        params: [{ name: "prompt", in: "body", required: true, description: "Video prompt" }],
      },
    ],
  },
  {
    id: "gmail",
    name: "Gmail",
    category: "comms",
    description: "Read and send email",
    docs: "https://developers.google.com/gmail/api/reference/rest",
    key: "https://console.cloud.google.com/apis/credentials",
    base: "https://gmail.googleapis.com/gmail/v1",
    auth: bearer,
    tools: [
      {
        name: "List messages",
        description: "Search your inbox",
        method: "GET",
        path: "/users/me/messages",
        params: [{ name: "q", in: "query", description: "Gmail search query" }],
      },
      {
        name: "Get message",
        description: "Read one email",
        method: "GET",
        path: "/users/me/messages/{id}",
        params: [{ name: "id", in: "path", required: true, description: "Message id" }],
      },
    ],
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    category: "data",
    description: "Events and availability",
    docs: "https://developers.google.com/calendar/api/v3/reference",
    key: "https://console.cloud.google.com/apis/credentials",
    base: "https://www.googleapis.com/calendar/v3",
    auth: bearer,
    tools: [
      {
        name: "List events",
        description: "Upcoming events",
        method: "GET",
        path: "/calendars/primary/events",
        params: [{ name: "timeMin", in: "query", description: "RFC3339 start time" }],
      },
      { name: "List calendars", description: "Calendars you can access", method: "GET", path: "/users/me/calendarList" },
    ],
  },
  {
    id: "tripo",
    name: "Tripo AI",
    category: "media",
    description: "Text and image to 3D models",
    docs: "https://platform.tripo3d.ai/docs",
    key: "https://platform.tripo3d.ai/api-keys",
    base: "https://api.tripo3d.ai/v2/openapi",
    auth: bearer,
    tools: [
      {
        name: "Create 3D task",
        description: "Generate a 3D model",
        method: "POST",
        path: "/task",
        params: [
          { name: "type", in: "body", required: true, description: "e.g. text_to_model" },
          { name: "prompt", in: "body", required: true, description: "Prompt" },
        ],
      },
    ],
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "dev",
    description: "DNS, zones and Workers",
    docs: "https://developers.cloudflare.com/api/",
    key: "https://dash.cloudflare.com/profile/api-tokens",
    base: "https://api.cloudflare.com/client/v4",
    auth: bearer,
    tools: [
      { name: "List zones", description: "Domains on your account", method: "GET", path: "/zones" },
      { name: "Verify token", description: "Check the token works", method: "GET", path: "/user/tokens/verify" },
    ],
  },
  {
    id: "google-drive",
    name: "Google Drive",
    category: "data",
    description: "Files, folders and search",
    docs: "https://developers.google.com/drive/api/reference/rest/v3",
    key: "https://console.cloud.google.com/apis/credentials",
    base: "https://www.googleapis.com/drive/v3",
    auth: bearer,
    tools: [
      {
        name: "Search files",
        description: "Find files in Drive",
        method: "GET",
        path: "/files",
        params: [{ name: "q", in: "query", description: "Drive query, e.g. name contains 'report'" }],
      },
    ],
  },
  {
    id: "posthog",
    name: "PostHog",
    category: "data",
    description: "Product analytics and events",
    docs: "https://posthog.com/docs/api",
    key: "https://app.posthog.com/settings/user-api-keys",
    base: "https://app.posthog.com/api",
    auth: bearer,
    tools: [
      { name: "List projects", description: "Projects you can read", method: "GET", path: "/projects/" },
      {
        name: "List insights",
        description: "Saved insights in a project",
        method: "GET",
        path: "/projects/{project_id}/insights/",
        params: [{ name: "project_id", in: "path", required: true, description: "Project id" }],
      },
    ],
  },
  {
    id: "n8n",
    name: "n8n",
    category: "dev",
    description: "Workflows and executions",
    docs: "https://docs.n8n.io/api/",
    key: "https://app.n8n.cloud/",
    base: "https://api.n8n.cloud/api/v1",
    auth: { type: "header", name: "X-N8N-API-KEY" },
    tools: [
      { name: "List workflows", description: "Your workflows", method: "GET", path: "/workflows" },
      { name: "List executions", description: "Recent runs", method: "GET", path: "/executions" },
    ],
  },
  {
    id: "outlook-mail",
    name: "Outlook Mail",
    category: "comms",
    description: "Read and send Outlook email",
    docs: "https://learn.microsoft.com/graph/api/resources/mail-api-overview",
    key: "https://entra.microsoft.com/",
    base: "https://graph.microsoft.com/v1.0",
    auth: bearer,
    tools: [
      {
        name: "List messages",
        description: "Inbox messages",
        method: "GET",
        path: "/me/messages",
        params: [{ name: "$search", in: "query", description: "Search text" }],
      },
    ],
  },
  {
    id: "canva",
    name: "Canva",
    category: "media",
    description: "Designs, assets and exports",
    docs: "https://www.canva.dev/docs/connect/",
    key: "https://www.canva.com/developers/",
    base: "https://api.canva.com/rest/v1",
    auth: bearer,
    tools: [{ name: "List designs", description: "Designs in your account", method: "GET", path: "/designs" }],
  },
  {
    id: "webflow",
    name: "Webflow",
    category: "dev",
    description: "Sites, pages and CMS items",
    docs: "https://developers.webflow.com/data/reference",
    key: "https://webflow.com/dashboard/account/apps",
    base: "https://api.webflow.com/v2",
    auth: bearer,
    tools: [
      { name: "List sites", description: "Sites you can edit", method: "GET", path: "/sites" },
      {
        name: "List collections",
        description: "CMS collections of a site",
        method: "GET",
        path: "/sites/{site_id}/collections",
        params: [{ name: "site_id", in: "path", required: true, description: "Site id" }],
      },
    ],
  },
  {
    id: "outlook-calendar",
    name: "Outlook Calendar",
    category: "data",
    description: "Meetings and availability",
    docs: "https://learn.microsoft.com/graph/api/resources/calendar",
    key: "https://entra.microsoft.com/",
    base: "https://graph.microsoft.com/v1.0",
    auth: bearer,
    tools: [{ name: "List events", description: "Calendar events", method: "GET", path: "/me/events" }],
  },
  {
    id: "wix",
    name: "Wix",
    category: "dev",
    description: "Sites, stores and bookings",
    docs: "https://dev.wix.com/docs/rest",
    key: "https://manage.wix.com/account/api-keys",
    base: "https://www.wixapis.com",
    auth: { type: "header", name: "Authorization" },
    tools: [{ name: "List sites", description: "Sites on your account", method: "GET", path: "/site-list/v2/sites/query" }],
  },
  {
    id: "granola",
    name: "Granola",
    category: "data",
    description: "AI meeting notes",
    docs: "https://www.granola.ai/",
    key: "https://www.granola.ai/",
    base: "https://api.granola.ai/v1",
    auth: bearer,
    tools: [{ name: "List notes", description: "Recent meeting notes", method: "GET", path: "/documents" }],
  },
  {
    id: "fireflies",
    name: "Fireflies",
    category: "data",
    description: "Meeting transcripts and summaries",
    docs: "https://docs.fireflies.ai/",
    key: "https://app.fireflies.ai/integrations/custom/fireflies",
    base: "https://api.fireflies.ai",
    auth: bearer,
    tools: [
      {
        name: "Run query",
        description: "GraphQL query for transcripts",
        method: "POST",
        path: "/graphql",
        params: [{ name: "query", in: "body", required: true, description: "GraphQL query" }],
      },
    ],
  },
  {
    id: "tldv",
    name: "tl;dv",
    category: "data",
    description: "Meeting recordings and highlights",
    docs: "https://doc.tldv.io/",
    key: "https://tldv.io/app/settings/personal-settings/api-keys",
    base: "https://pasta.tldv.io/v1alpha1",
    auth: { type: "header", name: "x-api-key" },
    tools: [{ name: "List meetings", description: "Recorded meetings", method: "GET", path: "/meetings" }],
  },
  {
    id: "firecrawl",
    name: "Firecrawl",
    category: "data",
    description: "Scrape and crawl any website",
    docs: "https://docs.firecrawl.dev/api-reference",
    key: "https://www.firecrawl.dev/app/api-keys",
    base: "https://api.firecrawl.dev/v1",
    auth: bearer,
    tools: [
      {
        name: "Scrape page",
        description: "Get clean markdown for a URL",
        method: "POST",
        path: "/scrape",
        params: [{ name: "url", in: "body", required: true, description: "Page URL" }],
      },
      {
        name: "Crawl site",
        description: "Crawl a whole site",
        method: "POST",
        path: "/crawl",
        params: [{ name: "url", in: "body", required: true, description: "Start URL" }],
      },
    ],
  },
  {
    id: "todoist",
    name: "Todoist",
    category: "data",
    description: "Tasks and projects",
    docs: "https://developer.todoist.com/rest/v2/",
    key: "https://app.todoist.com/app/settings/integrations/developer",
    base: "https://api.todoist.com/rest/v2",
    auth: bearer,
    tools: [
      { name: "List tasks", description: "Active tasks", method: "GET", path: "/tasks" },
      {
        name: "Create task",
        description: "Add a task",
        method: "POST",
        path: "/tasks",
        params: [{ name: "content", in: "body", required: true, description: "Task text" }],
      },
    ],
  },
  {
    id: "polygon",
    name: "Polygon.io",
    category: "finance",
    description: "Stocks, crypto and forex market data",
    docs: "https://polygon.io/docs",
    key: "https://polygon.io/dashboard/api-keys",
    base: "https://api.polygon.io",
    auth: { type: "query", name: "apiKey" },
    tools: [
      {
        name: "Ticker snapshot",
        description: "Latest price for a ticker",
        method: "GET",
        path: "/v2/snapshot/locale/us/markets/stocks/tickers/{ticker}",
        params: [{ name: "ticker", in: "path", required: true, description: "e.g. AAPL" }],
      },
      {
        name: "Search tickers",
        description: "Find tickers",
        method: "GET",
        path: "/v3/reference/tickers",
        params: [{ name: "search", in: "query", description: "Search text" }],
      },
    ],
  },
  {
    id: "zoominfo",
    name: "ZoomInfo",
    category: "data",
    description: "B2B company and contact data",
    docs: "https://api-docs.zoominfo.com/",
    key: "https://www.zoominfo.com/",
    base: "https://api.zoominfo.com",
    auth: bearer,
    tools: [
      {
        name: "Search companies",
        description: "Look up companies",
        method: "POST",
        path: "/search/company",
        params: [{ name: "companyName", in: "body", required: true, description: "Company name" }],
      },
    ],
  },
  {
    id: "mailchimp",
    name: "Mailchimp Marketing",
    category: "comms",
    description: "Audiences and email campaigns",
    docs: "https://mailchimp.com/developer/marketing/api/",
    key: "https://admin.mailchimp.com/account/api/",
    base: "https://us1.api.mailchimp.com/3.0",
    auth: bearer,
    tools: [
      { name: "List audiences", description: "Your lists", method: "GET", path: "/lists" },
      { name: "List campaigns", description: "Recent campaigns", method: "GET", path: "/campaigns" },
    ],
  },
  {
    id: "apollo",
    name: "Apollo",
    category: "data",
    description: "Sales prospecting and enrichment",
    docs: "https://docs.apollo.io/reference",
    key: "https://app.apollo.io/#/settings/integrations/api",
    base: "https://api.apollo.io/api/v1",
    auth: { type: "header", name: "x-api-key" },
    tools: [
      {
        name: "Search people",
        description: "Find prospects",
        method: "POST",
        path: "/mixed_people/search",
        params: [{ name: "q_keywords", in: "body", description: "Search keywords" }],
      },
    ],
  },
  {
    id: "metabase",
    name: "Metabase",
    category: "data",
    description: "Dashboards and saved questions",
    docs: "https://www.metabase.com/docs/latest/api-documentation",
    key: "https://www.metabase.com/docs/latest/people-and-groups/api-keys",
    base: "https://metabase.example.com/api",
    auth: { type: "header", name: "x-api-key" },
    tools: [
      { name: "List dashboards", description: "Dashboards you can see", method: "GET", path: "/dashboard" },
      { name: "List cards", description: "Saved questions", method: "GET", path: "/card" },
    ],
  },
  {
    id: "explorium",
    name: "Explorium",
    category: "data",
    description: "Business data enrichment",
    docs: "https://developers.explorium.ai/",
    key: "https://app.explorium.ai/",
    base: "https://api.explorium.ai/v1",
    auth: { type: "header", name: "api_key" },
    tools: [
      {
        name: "Match business",
        description: "Resolve a company to its record",
        method: "POST",
        path: "/businesses/match",
        params: [{ name: "businesses_to_match", in: "body", required: true, description: "Companies to match" }],
      },
    ],
  },
  {
    id: "jsonbin",
    name: "JSONBin.io",
    category: "dev",
    description: "Simple hosted JSON storage",
    docs: "https://jsonbin.io/api-reference",
    key: "https://jsonbin.io/api-keys",
    base: "https://api.jsonbin.io/v3",
    auth: { type: "header", name: "X-Master-Key" },
    tools: [
      {
        name: "Read bin",
        description: "Read stored JSON",
        method: "GET",
        path: "/b/{bin_id}",
        params: [{ name: "bin_id", in: "path", required: true, description: "Bin id" }],
      },
      {
        name: "Create bin",
        description: "Store a JSON document",
        method: "POST",
        path: "/b",
        params: [{ name: "data", in: "body", required: true, description: "JSON body" }],
      },
    ],
  },
  {
    id: "heygen",
    name: "HeyGen",
    category: "media",
    description: "AI avatar videos",
    docs: "https://docs.heygen.com/reference",
    key: "https://app.heygen.com/settings?nav=API",
    base: "https://api.heygen.com",
    auth: { type: "header", name: "X-Api-Key" },
    tools: [
      { name: "List avatars", description: "Available avatars", method: "GET", path: "/v2/avatars" },
      {
        name: "Generate video",
        description: "Create an avatar video",
        method: "POST",
        path: "/v2/video/generate",
        params: [{ name: "video_inputs", in: "body", required: true, description: "Scene definition" }],
      },
    ],
  },
  {
    id: "github",
    name: "GitHub",
    category: "dev",
    description: "Repos, issues and pull requests",
    docs: "https://docs.github.com/rest",
    key: "https://github.com/settings/tokens",
    base: "https://api.github.com",
    auth: bearer,
    tools: [
      { name: "My repos", description: "Repositories you can access", method: "GET", path: "/user/repos" },
      {
        name: "Search code",
        description: "Search code on GitHub",
        method: "GET",
        path: "/search/code",
        params: [{ name: "q", in: "query", required: true, description: "Search query" }],
      },
      {
        name: "List issues",
        description: "Issues in a repository",
        method: "GET",
        path: "/repos/{owner}/{repo}/issues",
        params: [
          { name: "owner", in: "path", required: true, description: "Owner" },
          { name: "repo", in: "path", required: true, description: "Repository" },
        ],
      },
    ],
  },
  {
    id: "apify",
    name: "Apify",
    category: "data",
    description: "Run scrapers and automation actors",
    docs: "https://docs.apify.com/api/v2",
    key: "https://console.apify.com/account/integrations",
    base: "https://api.apify.com/v2",
    auth: bearer,
    tools: [
      { name: "List actors", description: "Actors on your account", method: "GET", path: "/acts" },
      {
        name: "Run actor",
        description: "Start an actor run",
        method: "POST",
        path: "/acts/{actor_id}/runs",
        params: [{ name: "actor_id", in: "path", required: true, description: "Actor id" }],
      },
    ],
  },
];


/** What each service actually asks for, with its own field names.
 *  Anything not listed here takes a single API key. */
const CREDENTIALS: Record<string, ApiAppCredential[]> = {
  slack: [{ name: "apiKey", label: "Bot user OAuth token", example: "xoxb-…", secret: true }],
  notion: [
    { name: "apiKey", label: "Internal integration secret", example: "ntn_…", secret: true },
  ],
  zapier: [{ name: "apiKey", label: "Zapier NLA API key", secret: true }],
  asana: [{ name: "apiKey", label: "Personal access token", secret: true }],
  monday: [{ name: "apiKey", label: "API token (v2)", secret: true }],
  make: [
    { name: "apiKey", label: "API token", secret: true },
    { name: "zone", label: "Zone", description: "The part before make.com in your URL, e.g. eu1", example: "eu1" },
  ],
  linear: [{ name: "apiKey", label: "Personal API key", example: "lin_api_…", secret: true }],
  atlassian: [
    { name: "email", label: "Atlassian account email" },
    { name: "apiKey", label: "API token", secret: true },
  ],
  clickup: [{ name: "apiKey", label: "Personal API token", example: "pk_…", secret: true }],
  openai: [{ name: "apiKey", label: "Secret key", example: "sk-…", secret: true }],
  supabase: [
    {
      name: "apiKey",
      label: "Personal access token",
      description: "Account → Access tokens. Used for the Management API (projects, functions).",
      example: "sbp_…",
      secret: true,
    },
  ],
  vercel: [{ name: "apiKey", label: "Access token", secret: true }],
  anthropic: [{ name: "apiKey", label: "API key", example: "sk-ant-…", secret: true }],
  neon: [{ name: "apiKey", label: "API key", secret: true }],
  gemini: [{ name: "apiKey", label: "Google AI Studio API key", secret: true }],
  "prisma-postgres": [{ name: "apiKey", label: "Service token", secret: true }],
  sentry: [{ name: "apiKey", label: "Auth token", secret: true }],
  huggingface: [{ name: "apiKey", label: "Access token", example: "hf_…", secret: true }],
  perplexity: [{ name: "apiKey", label: "API key", example: "pplx-…", secret: true }],
  cohere: [{ name: "apiKey", label: "API key", secret: true }],
  hubspot: [{ name: "apiKey", label: "Private app access token", example: "pat-…", secret: true }],
  intercom: [{ name: "apiKey", label: "Access token", secret: true }],
  elevenlabs: [{ name: "apiKey", label: "API key", secret: true }],
  stripe: [{ name: "apiKey", label: "Secret key", example: "sk_live_…", secret: true }],
  grok: [{ name: "apiKey", label: "xAI API key", example: "xai-…", secret: true }],
  paypal: [
    { name: "clientId", label: "Client ID" },
    { name: "apiKey", label: "Client secret", secret: true },
  ],
  openrouter: [{ name: "apiKey", label: "API key", example: "sk-or-…", secret: true }],
  revenuecat: [{ name: "apiKey", label: "Secret API key (v2)", secret: true }],
  ahrefs: [{ name: "apiKey", label: "API token", secret: true }],
  close: [{ name: "apiKey", label: "API key", secret: true }],
  xero: [
    { name: "apiKey", label: "Access token", secret: true },
    { name: "tenantId", label: "Tenant ID", description: "The organisation the token should act on" },
  ],
  similarweb: [{ name: "apiKey", label: "API key", secret: true }],
  dropbox: [{ name: "apiKey", label: "Access token", example: "sl.…", secret: true }],
  flux: [{ name: "apiKey", label: "BFL API key", secret: true }],
  airtable: [{ name: "apiKey", label: "Personal access token", example: "pat…", secret: true }],
  dify: [{ name: "apiKey", label: "App API key", example: "app-…", secret: true }],
  kling: [{ name: "apiKey", label: "API token (JWT)", secret: true }],
  gmail: [
    {
      name: "apiKey",
      label: "OAuth access token",
      description: "Token with the gmail.readonly / gmail.send scope",
      secret: true,
    },
  ],
  "google-calendar": [
    { name: "apiKey", label: "OAuth access token", description: "Token with the calendar scope", secret: true },
  ],
  "google-drive": [
    { name: "apiKey", label: "OAuth access token", description: "Token with the drive scope", secret: true },
  ],
  tripo: [{ name: "apiKey", label: "API key", example: "tsk_…", secret: true }],
  cloudflare: [{ name: "apiKey", label: "API token", secret: true }],
  posthog: [{ name: "apiKey", label: "Personal API key", example: "phx_…", secret: true }],
  n8n: [
    { name: "apiKey", label: "API key", secret: true },
    { name: "host", label: "Instance host", description: "Your n8n host, e.g. myteam.app.n8n.cloud", example: "myteam.app.n8n.cloud" },
  ],
  "outlook-mail": [
    { name: "apiKey", label: "Microsoft Graph access token", description: "Token with the Mail.Read scope", secret: true },
  ],
  canva: [{ name: "apiKey", label: "Access token", secret: true }],
  webflow: [{ name: "apiKey", label: "Site API token", secret: true }],
  "outlook-calendar": [
    { name: "apiKey", label: "Microsoft Graph access token", description: "Token with the Calendars.Read scope", secret: true },
  ],
  wix: [
    { name: "apiKey", label: "API key", secret: true },
    { name: "siteId", label: "Site ID" },
  ],
  granola: [{ name: "apiKey", label: "API token", secret: true }],
  fireflies: [{ name: "apiKey", label: "API key", secret: true }],
  tldv: [{ name: "apiKey", label: "API key", secret: true }],
  firecrawl: [{ name: "apiKey", label: "API key", example: "fc-…", secret: true }],
  todoist: [{ name: "apiKey", label: "API token", secret: true }],
  polygon: [{ name: "apiKey", label: "API key", secret: true }],
  zoominfo: [{ name: "apiKey", label: "JWT access token", secret: true }],
  mailchimp: [
    { name: "apiKey", label: "API key", secret: true },
    { name: "dc", label: "Server prefix", description: "The part after the dash in your key, e.g. us21", example: "us21" },
  ],
  apollo: [{ name: "apiKey", label: "API key", secret: true }],
  metabase: [
    { name: "apiKey", label: "API key", secret: true },
    { name: "host", label: "Metabase host", description: "e.g. metabase.mycompany.com", example: "metabase.mycompany.com" },
  ],
  explorium: [{ name: "apiKey", label: "API key", secret: true }],
  jsonbin: [{ name: "apiKey", label: "Master key", secret: true }],
  heygen: [{ name: "apiKey", label: "API key", secret: true }],
  github: [{ name: "apiKey", label: "Personal access token", example: "ghp_…", secret: true }],
  apify: [{ name: "apiKey", label: "API token", example: "apify_api_…", secret: true }],
};

/** Services whose host depends on the account, filled from the fields above. */
const HOSTS: Record<string, string> = {
  make: "https://${zone}.make.com/api/v2",
  n8n: "https://${host}/api/v1",
  mailchimp: "https://${dc}.api.mailchimp.com/3.0",
  metabase: "https://${host}/api",
};

/** Brand mark from the service's own domain, for apps the registry misses. */
function brandIcon(seed: Seed): string {
  const host = new URL(seed.docs || seed.base).hostname.replace(
    /^(api|api-m|www|app|console|dashboard|platform|graph|open|developer|developers|docs|docs-|cloud)\./,
    "",
  );
  return `https://icons.duckduckgo.com/ip3/${host}.ico`;
}

/** The credential travels exactly the way each service documents it. */
function buildTemplate(seed: Seed) {
  const fields = CREDENTIALS[seed.id] ?? [];
  const basic = fields.some((f) => f.name === "email");
  if (basic) return undefined; // handled by the auth scheme below
  if (seed.auth.type === "query") return { params: { [seed.auth.name]: "${apiKey}" } };
  return { headers: { [seed.auth.name]: `${seed.auth.prefix ?? ""}\${apiKey}` } };
}

/** The Manus connector line-up, as key-based API apps. */
export const MANUS_APPS: ApiApp[] = SEEDS.map((seed) => ({
  id: seed.id,
  name: seed.name,
  category: seed.category,
  description: seed.description,
  docsUrl: seed.docs,
  keyUrl: seed.key,
  baseUrl: HOSTS[seed.id] ?? seed.base,
  auth: seed.auth,
  credentials: CREDENTIALS[seed.id] ?? [
    { name: "apiKey", label: "API key", secret: true },
  ],
  authTemplate: buildTemplate(seed),
  logo: seed.icon ?? serviceLogo(seed.name) ?? brandIcon(seed),
  tools: seed.tools.map((tool) => ({
    name: tool.name,
    description: tool.description,
    method: tool.method,
    path: tool.path,
    params: (tool.params ?? []).map((param) => ({
      name: param.name,
      in: param.in,
      required: Boolean(param.required),
      description: param.description,
    })),
  })),
}));
